/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello */

#ifndef _Included_Hello
#define _Included_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hello
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Hello_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     Hello
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_Hello_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Hello
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Hello_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Hello
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Hello_intArrayMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Hello
 * Method:    byteArrayMethod
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Hello_byteArrayMethod
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     Hello
 * Method:    bytebufferMethod
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_Hello_bytebufferMethod
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
